name: ably_flutter_integration_test
description: Integration tests for Ably Flutter plugin.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ably_flutter:
    path: ".."

  args: ^2.3.1
  enum_to_string: ^2.0.1
  http: ^0.13.4

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: ^1.21.1
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
