name: ably_flutter_example
description: Demonstrates how to use the Ably Flutter plugin.
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: "2.8.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  retry: ^3.1.0
  rxdart: ^0.27.1
  async: ^2.6.1
  stream_transform: ^2.0.0
  enum_to_string: ^2.0.1
  flutter_local_notifications: ^9.2.0
  fluttertoast: 8.0.2
  device_info_plus: ^3.2.1
  crypto: ^3.0.1
  flutter_hooks: ^0.18.2

dev_dependencies:
  ably_flutter:
    path: ../
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
