on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  ios:
    strategy:
      matrix:
        device: # Device names must be shown in `xcrun simctl list devices`
          - 'iPhone 15' # we are not specifying the iOS version as it tends to change
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: futureware-tech/simulator-action@v3
        with:
          model: ${{ matrix.device }}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24'
          cache: true

      # test_integration package depends on ably_flutter, so before we run integration
      # tests it's best to perform dependency update in both packages, to make sure that
      # integration tests are run with exactly the same dependencies as specified in
      # current version of ably_flutter package
      - name: 'Run Flutter Driver tests'
        timeout-minutes: 30
        run: |
          flutter pub get
          cd test_integration && flutter drive

  android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [24, 29]
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24'
          cache: true

      - name: 'Run Flutter Driver tests'
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            flutter pub get
            cd test_integration && flutter drive
